#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class mySlider (QtWidgets.QSlider):  # 自定义的QSlider类
 
    def __init__(self, parent=None):
        super (mySlider, self).__init__ (parent)
 
    def mousePressEvent(self, e):  ##禁用鼠标点击事件
        if e.buttons ():
            return

    
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outsideWidget = QtWidgets.QWidget(self.centralwidget)
        self.outsideWidget.setGeometry(QtCore.QRect(10, 0, 121, 561))
        self.outsideWidget.setObjectName("outsideWidget")
        self.label_6 = QtWidgets.QLabel(self.outsideWidget)
        self.label_6.setGeometry(QtCore.QRect(20, 532, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.outsideWidget)
        self.label_12.setGeometry(QtCore.QRect(17, 272, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.outsideWidget)
        self.label.setGeometry(QtCore.QRect(10, 11, 26, 19))
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.outsideWidget)
        self.label_10.setGeometry(QtCore.QRect(19, 324, 16, 16))
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.outsideWidget)
        self.label_19.setGeometry(QtCore.QRect(16, 220, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_8 = QtWidgets.QLabel(self.outsideWidget)
        self.label_8.setGeometry(QtCore.QRect(19, 480, 16, 16))
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.outsideWidget)
        self.label_13.setGeometry(QtCore.QRect(16, 246, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_18 = QtWidgets.QLabel(self.outsideWidget)
        self.label_18.setGeometry(QtCore.QRect(16, 142, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_9 = QtWidgets.QLabel(self.outsideWidget)
        self.label_9.setGeometry(QtCore.QRect(19, 350, 16, 16))
        self.label_9.setObjectName("label_9")
        self.label_17 = QtWidgets.QLabel(self.outsideWidget)
        self.label_17.setGeometry(QtCore.QRect(16, 116, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_5 = QtWidgets.QLabel(self.outsideWidget)
        self.label_5.setGeometry(QtCore.QRect(19, 454, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_21 = QtWidgets.QLabel(self.outsideWidget)
        self.label_21.setGeometry(QtCore.QRect(16, 169, 16, 16))
        self.label_21.setObjectName("label_21")
        self.label_3 = QtWidgets.QLabel(self.outsideWidget)
        self.label_3.setGeometry(QtCore.QRect(19, 402, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_20 = QtWidgets.QLabel(self.outsideWidget)
        self.label_20.setGeometry(QtCore.QRect(16, 194, 16, 16))
        self.label_20.setObjectName("label_20")
        self.label_11 = QtWidgets.QLabel(self.outsideWidget)
        self.label_11.setGeometry(QtCore.QRect(16, 298, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.outsideWidget)
        self.label_16.setGeometry(QtCore.QRect(16, 90, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_7 = QtWidgets.QLabel(self.outsideWidget)
        self.label_7.setGeometry(QtCore.QRect(19, 506, 16, 16))
        self.label_7.setObjectName("label_7")
        self.label_15 = QtWidgets.QLabel(self.outsideWidget)
        self.label_15.setGeometry(QtCore.QRect(16, 64, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.outsideWidget)
        self.label_14.setGeometry(QtCore.QRect(15, 38, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_2 = QtWidgets.QLabel(self.outsideWidget)
        self.label_2.setGeometry(QtCore.QRect(19, 376, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.outsideWidget)
        self.label_4.setGeometry(QtCore.QRect(19, 428, 16, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_2d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_2d.setGeometry(QtCore.QRect(80, 500, 41, 24))
        self.pushButton_2d.setObjectName("pushButton_2d")
        self.pushButton_11d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_11d.setGeometry(QtCore.QRect(80, 266, 41, 24))
        self.pushButton_11d.setObjectName("pushButton_11d")
        self.pushButton_19d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_19d.setGeometry(QtCore.QRect(80, 58, 41, 24))
        self.pushButton_19d.setObjectName("pushButton_19d")
        self.pushButton_7u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_7u.setGeometry(QtCore.QRect(40, 370, 41, 24))
        self.pushButton_7u.setObjectName("pushButton_7u")
        self.pushButton_14u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_14u.setGeometry(QtCore.QRect(40, 188, 41, 24))
        self.pushButton_14u.setObjectName("pushButton_14u")
        self.pushButton_15u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_15u.setGeometry(QtCore.QRect(40, 162, 41, 24))
        self.pushButton_15u.setObjectName("pushButton_15u")
        self.pushButton_14d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_14d.setGeometry(QtCore.QRect(80, 188, 41, 24))
        self.pushButton_14d.setObjectName("pushButton_14d")
        self.pushButton_2u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_2u.setGeometry(QtCore.QRect(40, 500, 41, 24))
        self.pushButton_2u.setObjectName("pushButton_2u")
        self.pushButton_6d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_6d.setGeometry(QtCore.QRect(80, 396, 41, 24))
        self.pushButton_6d.setObjectName("pushButton_6d")
        self.pushButton_13u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_13u.setGeometry(QtCore.QRect(40, 214, 41, 24))
        self.pushButton_13u.setObjectName("pushButton_13u")
        self.pushButton_17d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_17d.setGeometry(QtCore.QRect(80, 110, 41, 24))
        self.pushButton_17d.setObjectName("pushButton_17d")
        self.pushButton_11u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_11u.setGeometry(QtCore.QRect(40, 266, 41, 24))
        self.pushButton_11u.setObjectName("pushButton_11u")
        self.pushButton_4d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_4d.setGeometry(QtCore.QRect(80, 448, 41, 24))
        self.pushButton_4d.setObjectName("pushButton_4d")
        self.pushButton_18u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_18u.setGeometry(QtCore.QRect(40, 84, 41, 24))
        self.pushButton_18u.setObjectName("pushButton_18u")
        self.pushButton_15d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_15d.setGeometry(QtCore.QRect(80, 162, 41, 24))
        self.pushButton_15d.setObjectName("pushButton_15d")
        self.pushButton_16d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_16d.setGeometry(QtCore.QRect(80, 136, 41, 24))
        self.pushButton_16d.setObjectName("pushButton_16d")
        self.pushButton_8d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_8d.setGeometry(QtCore.QRect(80, 344, 41, 24))
        self.pushButton_8d.setObjectName("pushButton_8d")
        self.pushButton_5d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_5d.setGeometry(QtCore.QRect(80, 422, 41, 24))
        self.pushButton_5d.setObjectName("pushButton_5d")
        self.pushButton_19u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_19u.setGeometry(QtCore.QRect(40, 58, 41, 24))
        self.pushButton_19u.setObjectName("pushButton_19u")
        self.pushButton_17u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_17u.setGeometry(QtCore.QRect(40, 110, 41, 24))
        self.pushButton_17u.setObjectName("pushButton_17u")
        self.pushButton_20d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_20d.setGeometry(QtCore.QRect(80, 32, 41, 24))
        self.pushButton_20d.setObjectName("pushButton_20d")
        self.pushButton_10u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_10u.setGeometry(QtCore.QRect(40, 292, 41, 24))
        self.pushButton_10u.setObjectName("pushButton_10u")
        self.pushButton_18d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_18d.setGeometry(QtCore.QRect(80, 84, 41, 24))
        self.pushButton_18d.setObjectName("pushButton_18d")
        self.pushButton_3u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_3u.setGeometry(QtCore.QRect(40, 474, 41, 24))
        self.pushButton_3u.setObjectName("pushButton_3u")
        self.pushButton_8u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_8u.setGeometry(QtCore.QRect(40, 344, 41, 24))
        self.pushButton_8u.setObjectName("pushButton_8u")
        self.pushButton_5u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_5u.setGeometry(QtCore.QRect(40, 422, 41, 24))
        self.pushButton_5u.setObjectName("pushButton_5u")
        self.pushButton_3d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_3d.setGeometry(QtCore.QRect(80, 474, 41, 31))
        self.pushButton_3d.setObjectName("pushButton_3d")
        self.pushButton_12d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_12d.setGeometry(QtCore.QRect(80, 240, 41, 24))
        self.pushButton_12d.setObjectName("pushButton_12d")
        self.pushButton_16u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_16u.setGeometry(QtCore.QRect(40, 136, 41, 24))
        self.pushButton_16u.setObjectName("pushButton_16u")
        self.pushButton_7d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_7d.setGeometry(QtCore.QRect(80, 370, 41, 24))
        self.pushButton_7d.setObjectName("pushButton_7d")
        self.pushButton_1u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_1u.setGeometry(QtCore.QRect(40, 526, 41, 24))
        self.pushButton_1u.setObjectName("pushButton_1u")
        self.pushButton_12u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_12u.setGeometry(QtCore.QRect(40, 240, 41, 24))
        self.pushButton_12u.setObjectName("pushButton_12u")
        self.pushButton_6u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_6u.setGeometry(QtCore.QRect(40, 396, 41, 24))
        self.pushButton_6u.setObjectName("pushButton_6u")
        self.pushButton_9u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_9u.setGeometry(QtCore.QRect(40, 318, 41, 24))
        self.pushButton_9u.setObjectName("pushButton_9u")
        self.pushButton_4u = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_4u.setGeometry(QtCore.QRect(40, 448, 41, 24))
        self.pushButton_4u.setObjectName("pushButton_4u")
        self.pushButton_9d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_9d.setGeometry(QtCore.QRect(80, 318, 41, 24))
        self.pushButton_9d.setObjectName("pushButton_9d")
        self.pushButton_10d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_10d.setGeometry(QtCore.QRect(80, 292, 41, 24))
        self.pushButton_10d.setObjectName("pushButton_10d")
        self.pushButton_13d = QtWidgets.QPushButton(self.outsideWidget)
        self.pushButton_13d.setGeometry(QtCore.QRect(80, 214, 41, 24))
        self.pushButton_13d.setObjectName("pushButton_13d")
        self.widget_elevator1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_elevator1.setGeometry(QtCore.QRect(130, -10, 120, 571))
        self.widget_elevator1.setObjectName("widget_elevator1")
        self.elevator1_5 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_5.setGeometry(QtCore.QRect(10, 430, 51, 24))
        self.elevator1_5.setObjectName("elevator1_5")
        self.elevator1_4 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_4.setGeometry(QtCore.QRect(10, 456, 51, 24))
        self.elevator1_4.setObjectName("elevator1_4")
        self.elevator1_2 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_2.setGeometry(QtCore.QRect(10, 508, 51, 24))
        self.elevator1_2.setObjectName("elevator1_2")
        self.elevator1_15 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_15.setGeometry(QtCore.QRect(10, 168, 51, 24))
        self.elevator1_15.setObjectName("elevator1_15")
        self.elevator1_13 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_13.setGeometry(QtCore.QRect(10, 221, 51, 24))
        self.elevator1_13.setObjectName("elevator1_13")
        self.elevator1_19 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_19.setGeometry(QtCore.QRect(10, 64, 51, 24))
        self.elevator1_19.setObjectName("elevator1_19")
        self.elevator1_16 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_16.setGeometry(QtCore.QRect(10, 142, 51, 24))
        self.elevator1_16.setObjectName("elevator1_16")
        self.elevator1_17 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_17.setGeometry(QtCore.QRect(10, 116, 51, 24))
        self.elevator1_17.setObjectName("elevator1_17")
        self.elevator1_7 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_7.setGeometry(QtCore.QRect(10, 377, 51, 25))
        self.elevator1_7.setObjectName("elevator1_7")
        self.elevator1_12 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_12.setGeometry(QtCore.QRect(10, 247, 51, 24))
        self.elevator1_12.setObjectName("elevator1_12")
        self.elevator1_1 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_1.setGeometry(QtCore.QRect(10, 534, 51, 24))
        self.elevator1_1.setObjectName("elevator1_1")
        self.elevator1_3 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_3.setGeometry(QtCore.QRect(10, 482, 51, 24))
        self.elevator1_3.setObjectName("elevator1_3")
        self.elevator1_9 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_9.setGeometry(QtCore.QRect(10, 325, 51, 24))
        self.elevator1_9.setObjectName("elevator1_9")
        self.elevator1_8 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_8.setGeometry(QtCore.QRect(10, 351, 51, 24))
        self.elevator1_8.setObjectName("elevator1_8")
        self.elevator1_14 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_14.setGeometry(QtCore.QRect(10, 194, 51, 25))
        self.elevator1_14.setObjectName("elevator1_14")
        self.elevator1_10 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_10.setGeometry(QtCore.QRect(10, 299, 51, 24))
        self.elevator1_10.setObjectName("elevator1_10")
        self.elevator1_6 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_6.setGeometry(QtCore.QRect(10, 404, 51, 24))
        self.elevator1_6.setObjectName("elevator1_6")
        self.elevator1_11 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_11.setGeometry(QtCore.QRect(10, 273, 51, 24))
        self.elevator1_11.setObjectName("elevator1_11")
        self.elevator1_18 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_18.setGeometry(QtCore.QRect(10, 90, 51, 24))
        self.elevator1_18.setObjectName("elevator1_18")
        self.elevator1_20 = QtWidgets.QPushButton(self.widget_elevator1)
        self.elevator1_20.setGeometry(QtCore.QRect(10, 37, 51, 25))
        self.elevator1_20.setObjectName("elevator1_20")
        self.elevator1Slider = mySlider(self.widget_elevator1)
        self.elevator1Slider.setGeometry(QtCore.QRect(90, 40, 22, 520))
        self.elevator1Slider.setOrientation(QtCore.Qt.Vertical)
        self.elevator1Slider.setObjectName("elevator1Slider")
        self.widget_elevator2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_elevator2.setGeometry(QtCore.QRect(260, -10, 120, 571))
        self.widget_elevator2.setObjectName("widget_elevator2")
        self.elevator2_5 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_5.setGeometry(QtCore.QRect(10, 430, 51, 24))
        self.elevator2_5.setObjectName("elevator2_5")
        self.elevator2_4 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_4.setGeometry(QtCore.QRect(10, 456, 51, 24))
        self.elevator2_4.setObjectName("elevator2_4")
        self.elevator2_2 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_2.setGeometry(QtCore.QRect(10, 508, 51, 24))
        self.elevator2_2.setObjectName("elevator2_2")
        self.elevator2_15 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_15.setGeometry(QtCore.QRect(10, 168, 51, 24))
        self.elevator2_15.setObjectName("elevator2_15")
        self.elevator2_13 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_13.setGeometry(QtCore.QRect(10, 221, 51, 24))
        self.elevator2_13.setObjectName("elevator2_13")
        self.elevator2_19 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_19.setGeometry(QtCore.QRect(10, 64, 51, 24))
        self.elevator2_19.setObjectName("elevator2_19")
        self.elevator2_16 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_16.setGeometry(QtCore.QRect(10, 142, 51, 24))
        self.elevator2_16.setObjectName("elevator2_16")
        self.elevator2_17 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_17.setGeometry(QtCore.QRect(10, 116, 51, 24))
        self.elevator2_17.setObjectName("elevator2_17")
        self.elevator2_7 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_7.setGeometry(QtCore.QRect(10, 377, 51, 25))
        self.elevator2_7.setObjectName("elevator2_7")
        self.elevator2_12 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_12.setGeometry(QtCore.QRect(10, 247, 51, 24))
        self.elevator2_12.setObjectName("elevator2_12")
        self.elevator2_1 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_1.setGeometry(QtCore.QRect(10, 534, 51, 24))
        self.elevator2_1.setObjectName("elevator2_1")
        self.elevator2_3 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_3.setGeometry(QtCore.QRect(10, 482, 51, 24))
        self.elevator2_3.setObjectName("elevator2_3")
        self.elevator2_9 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_9.setGeometry(QtCore.QRect(10, 325, 51, 24))
        self.elevator2_9.setObjectName("elevator2_9")
        self.elevator2_8 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_8.setGeometry(QtCore.QRect(10, 351, 51, 24))
        self.elevator2_8.setObjectName("elevator2_8")
        self.elevator2_14 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_14.setGeometry(QtCore.QRect(10, 194, 51, 25))
        self.elevator2_14.setObjectName("elevator2_14")
        self.elevator2_10 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_10.setGeometry(QtCore.QRect(10, 299, 51, 24))
        self.elevator2_10.setObjectName("elevator2_10")
        self.elevator2_6 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_6.setGeometry(QtCore.QRect(10, 404, 51, 24))
        self.elevator2_6.setObjectName("elevator2_6")
        self.elevator2_11 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_11.setGeometry(QtCore.QRect(10, 273, 51, 24))
        self.elevator2_11.setObjectName("elevator2_11")
        self.elevator2_18 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_18.setGeometry(QtCore.QRect(10, 90, 51, 24))
        self.elevator2_18.setObjectName("elevator2_18")
        self.elevator2_20 = QtWidgets.QPushButton(self.widget_elevator2)
        self.elevator2_20.setGeometry(QtCore.QRect(10, 37, 51, 25))
        self.elevator2_20.setObjectName("elevator2_20")
        self.elevator2Slider = mySlider(self.widget_elevator2)
        self.elevator2Slider.setGeometry(QtCore.QRect(90, 40, 22, 520))
        self.elevator2Slider.setOrientation(QtCore.Qt.Vertical)
        self.elevator2Slider.setObjectName("elevator2Slider")
        self.widget_elevator3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_elevator3.setGeometry(QtCore.QRect(390, -10, 120, 571))
        self.widget_elevator3.setObjectName("widget_elevator3")
        self.elevator3_5 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_5.setGeometry(QtCore.QRect(10, 430, 51, 24))
        self.elevator3_5.setObjectName("elevator3_5")
        self.elevator3_4 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_4.setGeometry(QtCore.QRect(10, 456, 51, 24))
        self.elevator3_4.setObjectName("elevator3_4")
        self.elevator3_2 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_2.setGeometry(QtCore.QRect(10, 508, 51, 24))
        self.elevator3_2.setObjectName("elevator3_2")
        self.elevator3_15 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_15.setGeometry(QtCore.QRect(10, 168, 51, 24))
        self.elevator3_15.setObjectName("elevator3_15")
        self.elevator3_13 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_13.setGeometry(QtCore.QRect(10, 221, 51, 24))
        self.elevator3_13.setObjectName("elevator3_13")
        self.elevator3_19 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_19.setGeometry(QtCore.QRect(10, 64, 51, 24))
        self.elevator3_19.setObjectName("elevator3_19")
        self.elevator3_16 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_16.setGeometry(QtCore.QRect(10, 142, 51, 24))
        self.elevator3_16.setObjectName("elevator3_16")
        self.elevator3_17 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_17.setGeometry(QtCore.QRect(10, 116, 51, 24))
        self.elevator3_17.setObjectName("elevator3_17")
        self.elevator3_7 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_7.setGeometry(QtCore.QRect(10, 377, 51, 25))
        self.elevator3_7.setObjectName("elevator3_7")
        self.elevator3_12 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_12.setGeometry(QtCore.QRect(10, 247, 51, 24))
        self.elevator3_12.setObjectName("elevator3_12")
        self.elevator3_1 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_1.setGeometry(QtCore.QRect(10, 534, 51, 24))
        self.elevator3_1.setObjectName("elevator3_1")
        self.elevator3_3 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_3.setGeometry(QtCore.QRect(10, 482, 51, 24))
        self.elevator3_3.setObjectName("elevator3_3")
        self.elevator3_9 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_9.setGeometry(QtCore.QRect(10, 325, 51, 24))
        self.elevator3_9.setObjectName("elevator3_9")
        self.elevator3_8 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_8.setGeometry(QtCore.QRect(10, 351, 51, 24))
        self.elevator3_8.setObjectName("elevator3_8")
        self.elevator3_14 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_14.setGeometry(QtCore.QRect(10, 194, 51, 25))
        self.elevator3_14.setObjectName("elevator3_14")
        self.elevator3_10 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_10.setGeometry(QtCore.QRect(10, 299, 51, 24))
        self.elevator3_10.setObjectName("elevator3_10")
        self.elevator3_6 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_6.setGeometry(QtCore.QRect(10, 404, 51, 24))
        self.elevator3_6.setObjectName("elevator3_6")
        self.elevator3_11 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_11.setGeometry(QtCore.QRect(10, 273, 51, 24))
        self.elevator3_11.setObjectName("elevator3_11")
        self.elevator3_18 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_18.setGeometry(QtCore.QRect(10, 90, 51, 24))
        self.elevator3_18.setObjectName("elevator3_18")
        self.elevator3_20 = QtWidgets.QPushButton(self.widget_elevator3)
        self.elevator3_20.setGeometry(QtCore.QRect(10, 37, 51, 25))
        self.elevator3_20.setObjectName("elevator3_20")
        self.elevator3Slider = mySlider(self.widget_elevator3)
        self.elevator3Slider.setGeometry(QtCore.QRect(90, 40, 22, 520))
        self.elevator3Slider.setOrientation(QtCore.Qt.Vertical)
        self.elevator3Slider.setObjectName("elevator3Slider")
        self.widget_elevator4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_elevator4.setGeometry(QtCore.QRect(520, -10, 120, 571))
        self.widget_elevator4.setObjectName("widget_elevator4")
        self.elevator4_5 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_5.setGeometry(QtCore.QRect(10, 430, 51, 24))
        self.elevator4_5.setObjectName("elevator4_5")
        self.elevator4_4 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_4.setGeometry(QtCore.QRect(10, 456, 51, 24))
        self.elevator4_4.setObjectName("elevator4_4")
        self.elevator4_2 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_2.setGeometry(QtCore.QRect(10, 508, 51, 24))
        self.elevator4_2.setObjectName("elevator4_2")
        self.elevator4_15 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_15.setGeometry(QtCore.QRect(10, 168, 51, 24))
        self.elevator4_15.setObjectName("elevator4_15")
        self.elevator4_13 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_13.setGeometry(QtCore.QRect(10, 221, 51, 24))
        self.elevator4_13.setObjectName("elevator4_13")
        self.elevator4_19 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_19.setGeometry(QtCore.QRect(10, 64, 51, 24))
        self.elevator4_19.setObjectName("elevator4_19")
        self.elevator4_16 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_16.setGeometry(QtCore.QRect(10, 142, 51, 24))
        self.elevator4_16.setObjectName("elevator4_16")
        self.elevator4_17 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_17.setGeometry(QtCore.QRect(10, 116, 51, 24))
        self.elevator4_17.setObjectName("elevator4_17")
        self.elevator4_7 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_7.setGeometry(QtCore.QRect(10, 377, 51, 25))
        self.elevator4_7.setObjectName("elevator4_7")
        self.elevator4_12 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_12.setGeometry(QtCore.QRect(10, 247, 51, 24))
        self.elevator4_12.setObjectName("elevator4_12")
        self.elevator4_1 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_1.setGeometry(QtCore.QRect(10, 534, 51, 24))
        self.elevator4_1.setObjectName("elevator4_1")
        self.elevator4_3 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_3.setGeometry(QtCore.QRect(10, 482, 51, 24))
        self.elevator4_3.setObjectName("elevator4_3")
        self.elevator4_9 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_9.setGeometry(QtCore.QRect(10, 325, 51, 24))
        self.elevator4_9.setObjectName("elevator4_9")
        self.elevator4_8 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_8.setGeometry(QtCore.QRect(10, 351, 51, 24))
        self.elevator4_8.setObjectName("elevator4_8")
        self.elevator4_14 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_14.setGeometry(QtCore.QRect(10, 194, 51, 25))
        self.elevator4_14.setObjectName("elevator4_14")
        self.elevator4_10 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_10.setGeometry(QtCore.QRect(10, 299, 51, 24))
        self.elevator4_10.setObjectName("elevator4_10")
        self.elevator4_6 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_6.setGeometry(QtCore.QRect(10, 404, 51, 24))
        self.elevator4_6.setObjectName("elevator4_6")
        self.elevator4_11 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_11.setGeometry(QtCore.QRect(10, 273, 51, 24))
        self.elevator4_11.setObjectName("elevator4_11")
        self.elevator4_18 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_18.setGeometry(QtCore.QRect(10, 90, 51, 24))
        self.elevator4_18.setObjectName("elevator4_18")
        self.elevator4_20 = QtWidgets.QPushButton(self.widget_elevator4)
        self.elevator4_20.setGeometry(QtCore.QRect(10, 37, 51, 25))
        self.elevator4_20.setObjectName("elevator4_20")
        self.elevator4Slider = mySlider(self.widget_elevator4)
        self.elevator4Slider.setGeometry(QtCore.QRect(90, 40, 22, 520))
        self.elevator4Slider.setOrientation(QtCore.Qt.Vertical)
        self.elevator4Slider.setObjectName("elevator4Slider")
        self.widget_elevator5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_elevator5.setGeometry(QtCore.QRect(650, -10, 120, 571))
        self.widget_elevator5.setObjectName("widget_elevator5")
        self.elevator5_5 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_5.setGeometry(QtCore.QRect(10, 430, 51, 24))
        self.elevator5_5.setObjectName("elevator5_5")
        self.elevator5_4 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_4.setGeometry(QtCore.QRect(10, 456, 51, 24))
        self.elevator5_4.setObjectName("elevator5_4")
        self.elevator5_2 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_2.setGeometry(QtCore.QRect(10, 508, 51, 24))
        self.elevator5_2.setObjectName("elevator5_2")
        self.elevator5_15 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_15.setGeometry(QtCore.QRect(10, 168, 51, 24))
        self.elevator5_15.setObjectName("elevator5_15")
        self.elevator5_13 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_13.setGeometry(QtCore.QRect(10, 221, 51, 24))
        self.elevator5_13.setObjectName("elevator5_13")
        self.elevator5_19 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_19.setGeometry(QtCore.QRect(10, 64, 51, 24))
        self.elevator5_19.setObjectName("elevator5_19")
        self.elevator5_16 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_16.setGeometry(QtCore.QRect(10, 142, 51, 24))
        self.elevator5_16.setObjectName("elevator5_16")
        self.elevator5_17 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_17.setGeometry(QtCore.QRect(10, 116, 51, 24))
        self.elevator5_17.setObjectName("elevator5_17")
        self.elevator5_7 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_7.setGeometry(QtCore.QRect(10, 377, 51, 25))
        self.elevator5_7.setObjectName("elevator5_7")
        self.elevator5_12 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_12.setGeometry(QtCore.QRect(10, 247, 51, 24))
        self.elevator5_12.setObjectName("elevator5_12")
        self.elevator5_1 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_1.setGeometry(QtCore.QRect(10, 534, 51, 24))
        self.elevator5_1.setObjectName("elevator5_1")
        self.elevator5_3 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_3.setGeometry(QtCore.QRect(10, 482, 51, 24))
        self.elevator5_3.setObjectName("elevator5_3")
        self.elevator5_9 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_9.setGeometry(QtCore.QRect(10, 325, 51, 24))
        self.elevator5_9.setObjectName("elevator5_9")
        self.elevator5_8 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_8.setGeometry(QtCore.QRect(10, 351, 51, 24))
        self.elevator5_8.setObjectName("elevator5_8")
        self.elevator5_14 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_14.setGeometry(QtCore.QRect(10, 194, 51, 25))
        self.elevator5_14.setObjectName("elevator5_14")
        self.elevator5_10 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_10.setGeometry(QtCore.QRect(10, 299, 51, 24))
        self.elevator5_10.setObjectName("elevator5_10")
        self.elevator5_6 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_6.setGeometry(QtCore.QRect(10, 404, 51, 24))
        self.elevator5_6.setObjectName("elevator5_6")
        self.elevator5_11 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_11.setGeometry(QtCore.QRect(10, 273, 51, 24))
        self.elevator5_11.setObjectName("elevator5_11")
        self.elevator5_18 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_18.setGeometry(QtCore.QRect(10, 90, 51, 24))
        self.elevator5_18.setObjectName("elevator5_18")
        self.elevator5_20 = QtWidgets.QPushButton(self.widget_elevator5)
        self.elevator5_20.setGeometry(QtCore.QRect(10, 37, 51, 25))
        self.elevator5_20.setObjectName("elevator5_20")
        self.elevator5Slider = mySlider(self.widget_elevator5)
        self.elevator5Slider.setGeometry(QtCore.QRect(90, 40, 22, 520))
        self.elevator5Slider.setOrientation(QtCore.Qt.Vertical)
        self.elevator5Slider.setObjectName("elevator5Slider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_12.setText(_translate("MainWindow", "11"))
        self.label.setText(_translate("MainWindow", "楼层"))
        self.label_10.setText(_translate("MainWindow", "9"))
        self.label_19.setText(_translate("MainWindow", "13"))
        self.label_8.setText(_translate("MainWindow", "3"))
        self.label_13.setText(_translate("MainWindow", "12"))
        self.label_18.setText(_translate("MainWindow", "16"))
        self.label_9.setText(_translate("MainWindow", "8"))
        self.label_17.setText(_translate("MainWindow", "17"))
        self.label_5.setText(_translate("MainWindow", "4"))
        self.label_21.setText(_translate("MainWindow", "15"))
        self.label_3.setText(_translate("MainWindow", "6"))
        self.label_20.setText(_translate("MainWindow", "14"))
        self.label_11.setText(_translate("MainWindow", "10"))
        self.label_16.setText(_translate("MainWindow", "18"))
        self.label_7.setText(_translate("MainWindow", "2"))
        self.label_15.setText(_translate("MainWindow", "19"))
        self.label_14.setText(_translate("MainWindow", "20"))
        self.label_2.setText(_translate("MainWindow", "7"))
        self.label_4.setText(_translate("MainWindow", "5"))
        self.pushButton_2d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_11d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_19d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_7u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_14u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_15u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_14d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_2u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_6d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_13u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_17d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_11u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_4d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_18u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_15d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_16d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_8d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_5d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_19u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_17u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_20d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_10u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_18d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_3u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_8u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_5u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_3d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_12d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_16u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_7d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_1u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_12u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_6u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_9u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_4u.setText(_translate("MainWindow", "⬆️"))
        self.pushButton_9d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_10d.setText(_translate("MainWindow", "⬇️"))
        self.pushButton_13d.setText(_translate("MainWindow", "⬇️"))
        self.elevator1_5.setText(_translate("MainWindow", "5"))
        self.elevator1_4.setText(_translate("MainWindow", "4"))
        self.elevator1_2.setText(_translate("MainWindow", "2"))
        self.elevator1_15.setText(_translate("MainWindow", "15"))
        self.elevator1_13.setText(_translate("MainWindow", "13"))
        self.elevator1_19.setText(_translate("MainWindow", "19"))
        self.elevator1_16.setText(_translate("MainWindow", "16"))
        self.elevator1_17.setText(_translate("MainWindow", "17"))
        self.elevator1_7.setText(_translate("MainWindow", "7"))
        self.elevator1_12.setText(_translate("MainWindow", "12"))
        self.elevator1_1.setText(_translate("MainWindow", "1"))
        self.elevator1_3.setText(_translate("MainWindow", "3"))
        self.elevator1_9.setText(_translate("MainWindow", "9"))
        self.elevator1_8.setText(_translate("MainWindow", "8"))
        self.elevator1_14.setText(_translate("MainWindow", "14"))
        self.elevator1_10.setText(_translate("MainWindow", "10"))
        self.elevator1_6.setText(_translate("MainWindow", "6"))
        self.elevator1_11.setText(_translate("MainWindow", "11"))
        self.elevator1_18.setText(_translate("MainWindow", "18"))
        self.elevator1_20.setText(_translate("MainWindow", "20"))
        self.elevator2_5.setText(_translate("MainWindow", "5"))
        self.elevator2_4.setText(_translate("MainWindow", "4"))
        self.elevator2_2.setText(_translate("MainWindow", "2"))
        self.elevator2_15.setText(_translate("MainWindow", "15"))
        self.elevator2_13.setText(_translate("MainWindow", "13"))
        self.elevator2_19.setText(_translate("MainWindow", "19"))
        self.elevator2_16.setText(_translate("MainWindow", "16"))
        self.elevator2_17.setText(_translate("MainWindow", "17"))
        self.elevator2_7.setText(_translate("MainWindow", "7"))
        self.elevator2_12.setText(_translate("MainWindow", "12"))
        self.elevator2_1.setText(_translate("MainWindow", "1"))
        self.elevator2_3.setText(_translate("MainWindow", "3"))
        self.elevator2_9.setText(_translate("MainWindow", "9"))
        self.elevator2_8.setText(_translate("MainWindow", "8"))
        self.elevator2_14.setText(_translate("MainWindow", "14"))
        self.elevator2_10.setText(_translate("MainWindow", "10"))
        self.elevator2_6.setText(_translate("MainWindow", "6"))
        self.elevator2_11.setText(_translate("MainWindow", "11"))
        self.elevator2_18.setText(_translate("MainWindow", "18"))
        self.elevator2_20.setText(_translate("MainWindow", "20"))
        self.elevator3_5.setText(_translate("MainWindow", "5"))
        self.elevator3_4.setText(_translate("MainWindow", "4"))
        self.elevator3_2.setText(_translate("MainWindow", "2"))
        self.elevator3_15.setText(_translate("MainWindow", "15"))
        self.elevator3_13.setText(_translate("MainWindow", "13"))
        self.elevator3_19.setText(_translate("MainWindow", "19"))
        self.elevator3_16.setText(_translate("MainWindow", "16"))
        self.elevator3_17.setText(_translate("MainWindow", "17"))
        self.elevator3_7.setText(_translate("MainWindow", "7"))
        self.elevator3_12.setText(_translate("MainWindow", "12"))
        self.elevator3_1.setText(_translate("MainWindow", "1"))
        self.elevator3_3.setText(_translate("MainWindow", "3"))
        self.elevator3_9.setText(_translate("MainWindow", "9"))
        self.elevator3_8.setText(_translate("MainWindow", "8"))
        self.elevator3_14.setText(_translate("MainWindow", "14"))
        self.elevator3_10.setText(_translate("MainWindow", "10"))
        self.elevator3_6.setText(_translate("MainWindow", "6"))
        self.elevator3_11.setText(_translate("MainWindow", "11"))
        self.elevator3_18.setText(_translate("MainWindow", "18"))
        self.elevator3_20.setText(_translate("MainWindow", "20"))
        self.elevator4_5.setText(_translate("MainWindow", "5"))
        self.elevator4_4.setText(_translate("MainWindow", "4"))
        self.elevator4_2.setText(_translate("MainWindow", "2"))
        self.elevator4_15.setText(_translate("MainWindow", "15"))
        self.elevator4_13.setText(_translate("MainWindow", "13"))
        self.elevator4_19.setText(_translate("MainWindow", "19"))
        self.elevator4_16.setText(_translate("MainWindow", "16"))
        self.elevator4_17.setText(_translate("MainWindow", "17"))
        self.elevator4_7.setText(_translate("MainWindow", "7"))
        self.elevator4_12.setText(_translate("MainWindow", "12"))
        self.elevator4_1.setText(_translate("MainWindow", "1"))
        self.elevator4_3.setText(_translate("MainWindow", "3"))
        self.elevator4_9.setText(_translate("MainWindow", "9"))
        self.elevator4_8.setText(_translate("MainWindow", "8"))
        self.elevator4_14.setText(_translate("MainWindow", "14"))
        self.elevator4_10.setText(_translate("MainWindow", "10"))
        self.elevator4_6.setText(_translate("MainWindow", "6"))
        self.elevator4_11.setText(_translate("MainWindow", "11"))
        self.elevator4_18.setText(_translate("MainWindow", "18"))
        self.elevator4_20.setText(_translate("MainWindow", "20"))
        self.elevator5_5.setText(_translate("MainWindow", "5"))
        self.elevator5_4.setText(_translate("MainWindow", "4"))
        self.elevator5_2.setText(_translate("MainWindow", "2"))
        self.elevator5_15.setText(_translate("MainWindow", "15"))
        self.elevator5_13.setText(_translate("MainWindow", "13"))
        self.elevator5_19.setText(_translate("MainWindow", "19"))
        self.elevator5_16.setText(_translate("MainWindow", "16"))
        self.elevator5_17.setText(_translate("MainWindow", "17"))
        self.elevator5_7.setText(_translate("MainWindow", "7"))
        self.elevator5_12.setText(_translate("MainWindow", "12"))
        self.elevator5_1.setText(_translate("MainWindow", "1"))
        self.elevator5_3.setText(_translate("MainWindow", "3"))
        self.elevator5_9.setText(_translate("MainWindow", "9"))
        self.elevator5_8.setText(_translate("MainWindow", "8"))
        self.elevator5_14.setText(_translate("MainWindow", "14"))
        self.elevator5_10.setText(_translate("MainWindow", "10"))
        self.elevator5_6.setText(_translate("MainWindow", "6"))
        self.elevator5_11.setText(_translate("MainWindow", "11"))
        self.elevator5_18.setText(_translate("MainWindow", "18"))
        self.elevator5_20.setText(_translate("MainWindow", "20"))
